from typing import TypedDict, List, Dict, Annotated, Optional
import operator


class AgentState(TypedDict):
    """
    Shared state passed between all agents in the system.

    Attributes:
        goal (str): The main objective the system is trying to achieve.
        plan (List[str]): Ordered list of tasks generated by the planner.
        current_task (Optional[str]): The task currently being worked on.
                                      None when the plan is exhausted.

        research (str): Information gathered during the research phase.
        analysis (str): Results of the analysis performed on the research data.
        result (str): The final outcome after execution.

        history (List[Dict]): Append-only record of agent actions (managed by LangGraph).
        context (str): Compressed contextual information passed between agents.
        retrieved_memory (str): Long-term memory retrieved from the vector store.
        evaluation (str): The critic's assessment — "YES" if goal is satisfied, "NO" otherwise.
        selected_model (str): The Ollama model used by all agents.
        next_agent (str): The agent the manager decided to route to next.
    """

    goal: str
    plan: List[str]
    current_task: Optional[str]  # None when the plan is exhausted

    research: str
    analysis: str
    result: str

    history: Annotated[List[Dict], operator.add]
    context: str
    retrieved_memory: str
    evaluation: str
    selected_model: str
    next_agent: str  # routing decision from the manager